### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by sebthom**
This workflow runs on each commit/PR to verify it. When a commit is made to the main branch a GitHub pre-release named "latest" is created/updated containing binaries for linux/mac/win based on the last commit.

This also addresses #73

You can find an example here: https://github.com/sebthom/hashlink/releases/tag/latest

### CODE REVIEW

**Comment by Apprentice-Alchemist** [comment]
I would suggest using make for linux/osx, as cmake doesn't generate `ssl.hdll` currently.
Another issue is that cmake does not codesign the binaries on osx, meaning you wouldn't be able to use the debugger with them.
(Here's how I do it : <https://github.com/Apprentice-Alchemist/hashlink/blob/feature/github-ci/.github/workflows/main.yml>.)

**Comment by sebthom** [comment]
@Apprentice-Alchemist I don't mind to use make or cmake. what I like about the cmake approach is that it produces the final zip/tar.gz archives and I don't have to repeat the logic of how to package hashlink again.

Maybe the cmake config can be fixed somehow to sign macos binaries and generate the `ssl.hddl`?

**Comment by Apprentice-Alchemist** [comment]
On linux/macos you can also do `make release` to package binaries generated with `make`.

**Comment by ncannasse** [comment]
Hi ! Thanks for the contribution !
Yes I mostly maintain the `make` build, cmake was added as an alternative but is not entirely supported, so if you can switch to make I would be happy to merge it.

**Comment by sebthom** [comment]
I changed to make for linux/darwin and msbuild on windows.

An example of the generated artifacts can be found here https://github.com/sebthom/hashlink/releases/tag/latest

@Apprentice-Alchemist thanks for your build example, very helpful!

**Comment by sebthom** [comment]
@ncannasse could you please review and possibly merge this PR?

**Comment by sebthom** [comment]
@ncannasse could you please review and possibly merge this PR?

**Comment by ncannasse** [comment]
Merged ! thanks for the contrib !

**Comment by sebthom** [comment]
@ncannasse thanks for merging! apparently some things on the github runners as well as in the project config has changed since I created this GHA build config. I am going to provide another PR adjusting it accordingly

**Pull request merged**
