### PR TITLE
build: prevent fixing SDL2 header path for iOS

### PR DESCRIPTION
**Pull request by qkdreyer**
This PR allows me to prevent applying this git [patch](https://gist.github.com/qkdreyer/1a22b10fe4064554f724bf5a400fe470) in order to be able to compile hashlink for iOS using Xcode

### CODE REVIEW

**Comment by qkdreyer** [comment]
@ncannasse https://github.com/microsoft/azure-pipelines-image-generation/blob/master/README.md

**Comment by qkdreyer** [comment]
@ncannasse I've also successfully fixed azure pipelines

**Comment by ncannasse** [comment]
Could you keep /usr/local/include for backward compatibility (just in case) ?

**Comment by qkdreyer** [comment]
Done ✅

**Comment by tobil4sk** [comment]
@qkdreyer do you remember why this patch was needed? The `#include <SDL.h>` lines don't work when building on macos systems where SDL2 is installed in a way that expects `#include <SDL2/SDL.h>`.

Perhaps there is a way to patch this in a way that doesn't affect other builds.

**Comment by qkdreyer** [comment]
It was required for the iOS hashlink build IIRC

**Comment by tobil4sk** [comment]
Maybe we can make sure everything specific for the IOS builds is behind `#ifdef HL_IOS` blocks then. If you still have the dev environment, do you know where the include path is for SDL is when building for IOS? It is odd that it requires `#include <SDL.h>` instead of `#include <SDL2/SDL.h>`.

**Pull request merged**
