### PR TITLE
Fix semaphores on MacOS.

### LINKED ISSUE #502: Mac builds are broken
```
src/std/thread.c:111:19: error: conflicting types for 'hl_mutex_alloc'
HL_PRIM hl_mutex *hl_mutex_alloc( bool gc_thread ) {
                  ^
src/hl.h:689:18: note: previous declaration is here
HL_API hl_mutex *hl_mutex_alloc( bool gc_thread );
                 ^
src/std/thread.c:147:14: error: conflicting types for 'hl_mutex_try_acquire'
HL_PRIM bool hl_mutex_try_acquire( hl_mutex *l ) {
             ^
src/hl.h:691:13: note: previous declaration is here
HL_API bool hl_mutex_try_acquire( hl_mutex *l );
            ^
src/std/thread.c:226:13: error: conflicting types for 'hl_semaphore_try_acquire'
HL_API bool hl_semaphore_try_acquire(hl_semaphore *sem, vdynamic *timeout) {
            ^
src/hl.h:697:13: note: previous declaration is here
HL_API bool hl_semaphore_try_acquire(hl_semaphore *sem, vdynamic *timeout);
            ^
src/std/thread.c:235:13: warning: incompatible pointer types passing 'hl_semaphore *' (aka 'struct _hl_semaphore *') to parameter of type 'dispatch_semaphore_t _Nonnull' (aka 'struct dispatch_semaphore_s *') [-Wincompatible-pointer-types]
                   sem, dispatch_time(DISPATCH_TIME_NOW,
                   ^~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/dispatch/semaphore.h:89:46: note: passing argument to parameter 'dsema' here
dispatch_semaphore_wait(dispatch_semaphore_t dsema, dispatch_time_t timeout);
                                             ^
src/std/thread.c:267:28: warning: incompatible pointer types passing 'dispatch_semaphore_t *' (aka 'struct dispatch_semaphore_s **') to parameter of type 'dispatch_semaphore_t _Nonnull' (aka 'struct dispatch_semaphore_s *'); remove & [-Wincompatible-pointer-types]
        dispatch_semaphore_signal(&sem->sem);
                                  ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/dispatch/semaphore.h:111:48: note: passing argument to parameter 'dsema' here
dispatch_semaphore_signal(dispatch_semaphore_t dsema);
                                               ^
src/std/thread.c:283:3: error: implicit declaration of function 'sem_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                sem_destroy(&sem->sem);
                ^
src/std/thread.c:333:13: error: conflicting types for 'hl_condition_try_acquire'
HL_API bool hl_condition_try_acquire(hl_condition *cond) {
            ^
src/hl.h:703:13: note: previous declaration is here
HL_API bool hl_condition_try_acquire(hl_condition *cond);
            ^
src/std/thread.c:359:13: error: conflicting types for 'hl_condition_timed_wait'
HL_API bool hl_condition_timed_wait(hl_condition *cond, double timeout) {
            ^
src/hl.h:706:13: note: previous declaration is here
HL_API bool hl_condition_timed_wait(hl_condition *cond, double timeout);
            ^
src/std/thread.c:425:17: error: conflicting types for 'hl_tls_alloc'
HL_PRIM hl_tls *hl_tls_alloc( bool gc_value ) {
                ^
src/hl.h:711:16: note: previous declaration is here
HL_API hl_tls *hl_tls_alloc( bool gc_value );
               ^
src/std/thread.c:784:20: error: conflicting types for 'hl_thread_start'
HL_PRIM hl_thread *hl_thread_start( void *callback, void *param, bool withGC ) {
                   ^
src/hl.h:683:19: note: previous declaration is here
HL_API hl_thread *hl_thread_start( void *callback, void *param, bool withGC );
                  ^
src/std/thread.c:823:44: warning: incompatible pointer types passing 'bool *' to parameter of type 'bool *' (aka 'unsigned char *') [-Wincompatible-pointer-types]
        vdynamic *exc = hl_dyn_call_safe(c,NULL,0,&isExc);
                                                  ^~~~~~
src/hl.h:653:83: note: passing argument to parameter 'isException' here
HL_API vdynamic *hl_dyn_call_safe( vclosure *c, vdynamic **args, int nargs, bool *isException );
                                                                                  ^
3 warnings and 8 errors generated.
```

This comes from #495 @Apprentice-Alchemist

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
Closes #502.

### CODE REVIEW

**Comment by ncannasse** [comment]
Why are you removing some parts of hl.h ? I don't think that's required for the task.

**Comment by Apprentice-Alchemist** [comment]
Because defining `true`, `false` and `bool` in `hl.h` breaks things if `stdbool.h` is included later on by something else.
(In this case by `dispatch/dispatch.h`)
And with "break" I mean confusing errors such as:
```
src/std/thread.c:226:13: error: conflicting types for 'hl_semaphore_try_acquire'
HL_API bool hl_semaphore_try_acquire(hl_semaphore *sem, vdynamic *timeout) {
            ^
src/hl.h:697:13: note: previous declaration is here
HL_API bool hl_semaphore_try_acquire(hl_semaphore *sem, vdynamic *timeout);
```

**Comment by ncannasse** [comment]
You should then include these before hl.h ?

**Comment by Apprentice-Alchemist** [comment]
Alright.
Just to satisfy my curiosity then: is there any concrete reason for defining custom `true`,`false` and `bool`, instead of using `stdbool.h`?
(And for using `unsigned char` instead of `_Bool`.)

**Comment by ncannasse** [comment]
It seems that visual studio has stdbool.h, so you can actually use it :) can you change to the previous version, sorry ;)

**Comment by Apprentice-Alchemist** [comment]
Alright, back to the version using `stdbool.h`.

**Pull request merged**
