### PR TITLE
Semaphores and condition variables.

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
See HaxeFoundation/haxe#10503

### CODE REVIEW

**Comment by ncannasse** [comment]
Hello. As it's not part of the Haxe standard library, please create your own hdll for additional primitives.

**Comment by Aurel300** [comment]
@ncannasse The PR linked in the description (HaxeFoundation/haxe#10503) is adding semaphores to the stdlib and implementing it for all sys targets.

**Comment by ncannasse** [comment]
Ok. But first please make when you submit a PR not to change the formatting of existing files :)

**Comment by RealyUniqueName** [comment]
@ncannasse The PR in Haxe repo is ready. Could you please review this one?

**Comment by ncannasse** [comment]
Seems good, however should use tabs instead of spaces as other parts of the HL code ;)

**Comment by Apprentice-Alchemist** [comment]
Spaces have been replaced with tabs.
(You should consider adding a `.clang-format` file with the style you want.)

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
