### PR TITLE
SQLite lib

### PR DESCRIPTION
**Pull request by ConstNW**
ported neko sqlite lib
@ncannasse, could you please take a look at it

### CODE REVIEW

**Comment by ncannasse** [comment]
How sorry I was on holidays when this was posted and I completely overlooked it. Could you rebase on master so I can merge?

**Comment by ConstNW** [comment]
Sure. As soon as i get time on it i'll update pull request

**Comment by anissen** [comment]
Sorry to intrude but I believe that you can now [choose to rebase and merge the PR](https://github.com/blog/2243-rebase-and-merge-pull-requests) instead of merging it 😃

**Comment by Simn** [comment]
Indeed, but this particular PR can be neither merged nor rebased because there are conflicts.

**Comment by ConstNW** [comment]
I suppose code of that lib should be actualized and i'll do it ASAP :)

**Pull request closed without merging**
