### PR TITLE
added accelerometer events

### PR DESCRIPTION
**Pull request by josuigoa**

### CODE REVIEW

**Comment by ncannasse** [comment]
That patch seems to be dangerous as there does not seem to be any guarantee that the axis index reported by the joystick API does not overlap with a game controller button.

This is what I understand from
https://discourse.libsdl.org/t/difference-between-joysticks-and-game-controllers/24028/2

**Comment by josuigoa** [comment]
do you suggest to create a new event type (AccelerometerAxis, e.g.)?

**Comment by ncannasse** [comment]
It would also require events for adding/removing joysticks, etc.

**Comment by josuigoa** [comment]
I've implemented the joystick API. It is ok for you to mantain the ```SDL_SetHint(SDL_HINT_ACCELEROMETER_AS_JOYSTICK, "1");``` as is, or do you prefer to put it inside a conditional flag?

**Comment by ncannasse** [comment]
I guess the best would be to give access to the SDL_SetHint method from Haxe.

**Pull request merged**
