### PR TITLE
Easier build on M1 take 2

### PR DESCRIPTION
**Pull request by wynan**
This is based closely on [nullobsi](https://github.com/nullobsi) PR but addresses the issue [waaadim](https://github.com/waaadim) identified.

### CODE REVIEW

**Comment by wynan** [comment]
Let me know if there are any requested changes to this PR.

**Comment by ncannasse** [comment]
Removing `msse2 -mfpmath=sse` on Linux does not seem like a good idea ?

**Comment by wynan** [comment]
Thanks for the feedback. I'll work on the updates.

**Comment by wynan** [comment]
@Apprentice-Alchemist, let me know if you have any concerns with that approach.

**Comment by Apprentice-Alchemist** [comment]
Looks good to me.

**Comment by Simn** [comment]
I can't really review this, but it doesn't break CI and seems to make various people happy, so I'll merge it!

**Pull request merged**
