### PR TITLE
Restore basic debugging support on Linux.

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
It doesn't work perfectly yet (for example stepping in/out is still broken), but at least breakpoints and breaking on exceptions works again.

### CODE REVIEW

**Comment by ncannasse** [comment]
That seems overly complex. Why allowing several debuggers to connect ?

**Comment by rcstuber** [comment]
I think we should reopen and discuss this PR!
It looks valid for future Hashlink on ARM which is currently a work-in-progress by @Apprentice-Alchemist

**Comment by Jarrio** [comment]
> That seems overly complex. Why allowing several debuggers to connect ?

> It's been a while since I wrote the code, but iirc the whole background thread and condition variable dance is needed because there's no way (that I found) to `waitpid` with a timeout.

**Comment by Apprentice-Alchemist** [comment]
> > That seems overly complex. Why allowing several debuggers to connect ?
> 
> > It's been a while since I wrote the code, but iirc the whole background thread and condition variable dance is needed because there's no way (that I found) to `waitpid` with a timeout.

@Jarrio I was talking about my new implementation, not this one.

**Pull request closed without merging**
