### PR TITLE
Ensure consistent line endings: LF except Visual Studio files

### PR DESCRIPTION
**Pull request by dpeek**
Followed the guidance here, but not entirely sure this is the right config.
https://help.github.com/articles/dealing-with-line-endings

You can see some files were mixed line-endings, though perhaps `*.sln` and similar don't need to be CRLF?

Also worth noting that `.gitignore` currently ignores `/include/turbojpeg/x64/*` because of the `x64` entry – I suppose that needs to be more specific?

Happy to update if you know any git gurus that can advise...

### CODE REVIEW

**Comment by ncannasse** [comment]
Uhm that's a bit bigger than expected, I would like to avoid if possible whole-file-changes since it breaks git blame quite significantly.

So I think the git autocrlf should be set to "binary" (which means to keep "original" line endings, whatever the file was originally created with). 

Could you resubmit the PR with these changes?

**Comment by dpeek** [comment]
Not sure you can avoid a big patch here if you want consistency... browsing the source in VS Code detects about half the files as CRLF and the rest as LF (there is an indicator bottom right in the window).

And even then, converting to one or the other reveals that line endings are often mixed within files (which was what I originally stumbled on).

I think `core.autocrlf "binary"` just means that git doesn't do anything to the line endings, as you would want for executables, images etc.

Github suggests LF for text source and CRLF for files that will get created that way anyway like `*.sln`. In the end the main problem is the mixed endings though, as it creates misleading diffs when you make edits :(

Sorry for uncovering this rabbit hole!

**Comment by dpeek** [comment]
Example from main.c

Detected as CRLF by VSCode. But coverting to LF and back to CRLF gives this diff:

image

**Comment by dpeek** [comment]
So the smallest patch will be to convert files to the detected line-ending, but you'll still have a mix between files.

**Comment by ncannasse** [comment]
Yes I understand. I'm fine with mix between files. Not within the same file
though.

**Comment by dpeek** [comment]
Ok, I think this is the smallest patch to ensure no mixed endings.

Basically ensured files detected as CRLF were CRLF _only_ - there weren't any LF files with the same issue.

Unfortunately there is no .gitatttributes config that will prevent the problem from occurring again as the mix between CRLF and LF is more or less random.

Here are the bash commands I used to ensure consistency (requires sfk which is xplatform):

```
# find all files detected as CRLF and force CRLF
find . -path ./.git -prune -o -type f -exec file {} \; | grep "CRLF" | awk -F ':' '{ print $1 }' | xargs sfk addcr

# find all files detected as LF and force LF
find . -path ./.git -prune -o -type f -exec file {} \; | grep -v "CRLF" | awk -F ':' '{ print $1 }' | xargs sfk remcr
```

Here are the CRLF files currently in the repo (LF is more common):

```
./hlc.vcxproj
CR ./libhl.vcxproj.filters
./hlc.vcxproj.filters
./CMakeLists.txt
CR ./hl.vcxproj
./hl.vcxproj.filters
./LICENSE
./Dockerfile-i386
./Dockerfile
./Makefile
./include/vorbis/smallft.h
./include/vorbis/res0.c
./include/vorbis/ogg/ogg.h
CR ./include/vorbis/ogg/config_types.h
./include/vorbis/ogg/os_types.h
./include/vorbis/block.c
./include/vorbis/vorbis/vorbisfile.h
./include/vorbis/vorbis/codec.h
./include/vorbis/lookup.c
./include/vorbis/framing.c
./include/vorbis/misc.h
./include/vorbis/info.c
./include/vorbis/mdct.c
./include/vorbis/os.h
./include/vorbis/envelope.c
./include/vorbis/window.h
./include/vorbis/codebook.c
./include/vorbis/floor0.c
./include/vorbis/backends.h
./include/vorbis/lsp.h
./include/vorbis/bitrate.c
./include/vorbis/registry.h
./include/vorbis/psy.c
./include/vorbis/README
./include/vorbis/lpc.h
./include/vorbis/highlevel.h
./include/vorbis/smallft.c
./include/vorbis/lookup_data.h
./include/vorbis/scales.h
./include/vorbis/sharedbook.c
./include/vorbis/floor1.c
./include/vorbis/lookup.h
./include/vorbis/synthesis.c
./include/vorbis/envelope.h
./include/vorbis/masking.h
./include/vorbis/mdct.h
./include/vorbis/mapping0.c
./include/vorbis/psy.h
./include/vorbis/lpc.c
./include/vorbis/bitrate.h
./include/vorbis/lsp.c
./include/vorbis/bitwise.c
./include/vorbis/registry.c
./include/vorbis/vorbisfile.c
./include/vorbis/window.c
./include/vorbis/codec_internal.h
./include/vorbis/codebook.h
./include/libuv/LICENSE
./include/libuv/ChangeLog
./include/libuv/AUTHORS
./include/libuv/include/uv-threadpool.h
./include/libuv/include/uv.h
./include/libuv/include/uv-win.h
./include/libuv/include/uv-errno.h
./include/libuv/include/tree.h
./include/libuv/include/uv-version.h
./include/libuv/src/win/thread.c
./include/libuv/src/win/winapi.h
./include/libuv/src/win/async.c
./include/libuv/src/win/winsock.h
./include/libuv/src/win/internal.h
./include/libuv/src/win/timer.c
./include/libuv/src/win/process.c
./include/libuv/src/win/stream-inl.h
./include/libuv/src/win/pipe.c
./include/libuv/src/win/util.c
./include/libuv/src/win/loop-watcher.c
./include/libuv/src/win/handle.c
./include/libuv/src/win/poll.c
./include/libuv/src/win/udp.c
./include/libuv/src/win/fs.c
./include/libuv/src/win/process-stdio.c
./include/libuv/src/win/winsock.c
./include/libuv/src/win/core.c
./include/libuv/src/win/winapi.c
./include/libuv/src/win/snprintf.c
./include/libuv/src/win/tcp.c
./include/libuv/src/win/getaddrinfo.c
./include/libuv/src/win/error.c
./include/libuv/src/win/getnameinfo.c
./include/libuv/src/win/atomicops-inl.h
./include/libuv/src/win/tty.c
./include/libuv/src/win/fs-event.c
./include/libuv/src/win/req.c
./include/libuv/src/win/req-inl.h
./include/libuv/src/win/signal.c
./include/libuv/src/win/dl.c
./include/libuv/src/win/stream.c
./include/libuv/src/win/handle-inl.h
./include/libuv/src/uv-common.c
./include/libuv/src/threadpool.c
./include/libuv/src/version.c
./include/libuv/src/fs-poll.c
./include/libuv/src/inet.c
./include/libuv/src/heap-inl.h
./include/libuv/src/uv-common.h
./include/libuv/src/queue.h
./include/minimp3/LICENSE
./include/minimp3/README.md
./include/minimp3/minimp3.h
./include/mbedtls/LICENSE
./include/mbedtls/include/mbedtls/pem.h
./include/mbedtls/include/mbedtls/check_config.h
./include/mbedtls/include/mbedtls/error.h
./include/mbedtls/include/mbedtls/md2.h
./include/mbedtls/include/mbedtls/oid.h
./include/mbedtls/include/mbedtls/rsa_internal.h
./include/mbedtls/include/mbedtls/pkcs5.h
./include/mbedtls/include/mbedtls/ripemd160.h
./include/mbedtls/include/mbedtls/blowfish.h
./include/mbedtls/include/mbedtls/debug.h
./include/mbedtls/include/mbedtls/x509.h
./include/mbedtls/include/mbedtls/version.h
./include/mbedtls/include/mbedtls/ecp.h
./include/mbedtls/include/mbedtls/net.h
./include/mbedtls/include/mbedtls/cipher_internal.h
./include/mbedtls/include/mbedtls/md_internal.h
./include/mbedtls/include/mbedtls/base64.h
./include/mbedtls/include/mbedtls/pkcs11.h
./include/mbedtls/include/mbedtls/ssl_internal.h
./include/mbedtls/include/mbedtls/threading_alt.h
./include/mbedtls/include/mbedtls/asn1.h
./include/mbedtls/include/mbedtls/config.h
./include/mbedtls/include/mbedtls/memory_buffer_alloc.h
./include/mbedtls/include/mbedtls/x509_csr.h
./include/mbedtls/include/mbedtls/xtea.h
./include/mbedtls/include/mbedtls/threading.h
./include/mbedtls/include/mbedtls/compat-1.3.h
./include/mbedtls/include/mbedtls/md5.h
./include/mbedtls/include/mbedtls/timing.h
./include/mbedtls/include/mbedtls/arc4.h
./include/mbedtls/include/mbedtls/sha256.h
./include/mbedtls/include/mbedtls/ecdsa.h
./include/mbedtls/include/mbedtls/md.h
./include/mbedtls/include/mbedtls/cipher.h
./include/mbedtls/include/mbedtls/ecjpake.h
./include/mbedtls/include/mbedtls/net_sockets.h
./include/mbedtls/include/mbedtls/entropy.h
./include/mbedtls/include/mbedtls/pkcs12.h
./include/mbedtls/include/mbedtls/padlock.h
./include/mbedtls/include/mbedtls/sha512.h
./include/mbedtls/include/mbedtls/bn_mul.h
./include/mbedtls/include/mbedtls/pk.h
./include/mbedtls/include/mbedtls/ecp_internal.h
./include/mbedtls/include/mbedtls/ssl.h
./include/mbedtls/include/mbedtls/platform_time.h
./include/mbedtls/include/mbedtls/camellia.h
./include/mbedtls/include/mbedtls/md4.h
./include/mbedtls/include/mbedtls/x509_crt.h
./include/mbedtls/include/mbedtls/aes.h
./include/mbedtls/include/mbedtls/pk_internal.h
./include/mbedtls/include/mbedtls/ssl_cookie.h
./include/mbedtls/include/mbedtls/dhm.h
./include/mbedtls/include/mbedtls/aesni.h
./include/mbedtls/include/mbedtls/ctr_drbg.h
./include/mbedtls/include/mbedtls/des.h
./include/mbedtls/include/mbedtls/x509_crl.h
./include/mbedtls/include/mbedtls/ecdh.h
./include/mbedtls/include/mbedtls/sha1.h
./include/mbedtls/include/mbedtls/gcm.h
./include/mbedtls/include/mbedtls/certs.h
./include/mbedtls/include/mbedtls/rsa.h
./include/mbedtls/include/mbedtls/hmac_drbg.h
./include/mbedtls/include/mbedtls/ssl_ticket.h
./include/mbedtls/include/mbedtls/ssl_ciphersuites.h
./include/mbedtls/include/mbedtls/ssl_cache.h
./include/mbedtls/include/mbedtls/cmac.h
./include/mbedtls/include/mbedtls/platform.h
./include/mbedtls/include/mbedtls/bignum.h
./include/mbedtls/include/mbedtls/entropy_poll.h
./include/mbedtls/include/mbedtls/havege.h
./include/mbedtls/include/mbedtls/asn1write.h
./include/mbedtls/include/mbedtls/ccm.h
./include/mbedtls/library/x509_create.c
./include/mbedtls/library/x509_crt.c
./include/mbedtls/library/aes.c
./include/mbedtls/library/md4.c
./include/mbedtls/library/ssl_srv.c
./include/mbedtls/library/camellia.c
./include/mbedtls/library/pk_wrap.c
./include/mbedtls/library/pk.c
./include/mbedtls/library/ecdh.c
./include/mbedtls/library/ssl_tls.c
./include/mbedtls/library/x509_crl.c
./include/mbedtls/library/cipher_wrap.c
./include/mbedtls/library/des.c
./include/mbedtls/library/ssl_cookie.c
./include/mbedtls/library/ctr_drbg.c
./include/mbedtls/library/aesni.c
./include/mbedtls/library/dhm.c
./include/mbedtls/library/ssl_cache.c
./include/mbedtls/library/ssl_ciphersuites.c
./include/mbedtls/library/hmac_drbg.c
./include/mbedtls/library/rsa.c
./include/mbedtls/library/ssl_ticket.c
./include/mbedtls/library/asn1parse.c
./include/mbedtls/library/certs.c
./include/mbedtls/library/pkwrite.c
./include/mbedtls/library/gcm.c
./include/mbedtls/library/sha1.c
./include/mbedtls/library/asn1write.c
./include/mbedtls/library/havege.c
./include/mbedtls/library/ccm.c
./include/mbedtls/library/version_features.c
./include/mbedtls/library/entropy_poll.c
./include/mbedtls/library/x509write_csr.c
./include/mbedtls/library/platform.c
./include/mbedtls/library/cmac.c
./include/mbedtls/library/bignum.c
./include/mbedtls/library/pkparse.c
./include/mbedtls/library/debug.c
./include/mbedtls/library/ripemd160.c
./include/mbedtls/library/ssl_cli.c
./include/mbedtls/library/blowfish.c
./include/mbedtls/library/rsa_internal.c
./include/mbedtls/library/pkcs5.c
./include/mbedtls/library/pem.c
./include/mbedtls/library/oid.c
./include/mbedtls/library/error.c
./include/mbedtls/library/md2.c
./include/mbedtls/library/md_wrap.c
./include/mbedtls/library/x509_csr.c
./include/mbedtls/library/pkcs11.c
./include/mbedtls/library/base64.c
./include/mbedtls/library/memory_buffer_alloc.c
./include/mbedtls/library/ecp.c
./include/mbedtls/library/version.c
./include/mbedtls/library/x509.c
./include/mbedtls/library/sha256.c
./include/mbedtls/library/ecp_curves.c
./include/mbedtls/library/md5.c
./include/mbedtls/library/arc4.c
./include/mbedtls/library/timing.c
./include/mbedtls/library/xtea.c
./include/mbedtls/library/x509write_crt.c
./include/mbedtls/library/threading.c
./include/mbedtls/library/padlock.c
./include/mbedtls/library/pkcs12.c
./include/mbedtls/library/entropy.c
./include/mbedtls/library/net_sockets.c
./include/mbedtls/library/sha512.c
./include/mbedtls/library/md.c
./include/mbedtls/library/ecjpake.c
./include/mbedtls/library/cipher.c
./include/mbedtls/library/ecdsa.c
./include/mbedtls/apache-2.0.txt
./include/sqlite/README.md
./include/sqlite/.gitignore
./include/sqlite/src/sqlite3.c
./include/sqlite/src/sqlite3.h
./include/sqlite/src/sqlite3ext.h
./include/zlib/zutil.h
./include/zlib/inftrees.h
./include/zlib/inflate.c
./include/zlib/deflate.c
./include/zlib/inffixed.h
./include/zlib/trees.h
./include/zlib/inffast.h
./include/zlib/crc32.c
./include/zlib/README
./include/zlib/zutil.c
./include/zlib/deflate.h
./include/zlib/zlib.h
./include/zlib/inflate.h
./include/zlib/inftrees.c
./include/zlib/trees.c
./include/zlib/crc32.h
./include/zlib/inffast.c
./include/zlib/adler32.c
./include/zlib/zconf.h
./include/png/pnginfo.h
./include/png/pngrio.c
./include/png/pngerror.c
./include/png/pngwio.c
./include/png/pngstruct.h
./include/png/LICENSE
./include/png/pngtrans.c
./include/png/pngpriv.h
./include/png/pngwrite.c
./include/png/png.h
./include/png/README
./include/png/pngwutil.c
./include/png/pngwtran.c
./include/png/pnglibconf.h
./include/png/pngconf.h
./include/png/pngpread.c
./include/png/pngdebug.h
./include/png/pngread.c
./include/png/pngmem.c
./include/png/pngget.c
./include/png/png.c
./include/png/pngrtran.c
./include/png/pngrutil.c
./include/png/pngset.c
./include/README.md
./include/gl/glext.h
./include/pcre/pcre_compile.c
./include/pcre/ucp.h
./include/pcre/pcre_xclass.c
./include/pcre/pcre_ucd.c
CR ./include/pcre/config.h
./include/pcre/pcre_exec.c
./include/pcre/pcre_tables.c
./include/pcre/pcre16_ord2utf16.c
./include/pcre/pcre_string_utils.c
./include/pcre/pcre.h
./include/pcre/pcre_newline.c
./include/pcre/pcre_fullinfo.c
./include/pcre/pcre_dfa_exec.c
./include/pcre/pcre_globals.c
./include/pcre/pcre16_valid_utf16.c
./include/pcre/pcre_internal.h
./include/pcre/pcre_chartables.c
./include/mikktspace/mikktspace.c
./include/mikktspace/mikktspace.h
./include/turbojpeg/jsimd.c
./include/turbojpeg/jpeglib.h
./include/turbojpeg/jddctmgr.c
./include/turbojpeg/jdphuff.c
./include/turbojpeg/jerror.h
./include/turbojpeg/jidctfst.c
./include/turbojpeg/jpegcomp.h
./include/turbojpeg/jdatasrc.c
./include/turbojpeg/jdatasrc-tj.c
./include/turbojpeg/jdhuff.c
./include/turbojpeg/jdinput.c
./include/turbojpeg/jdtrans.c
./include/turbojpeg/jccolext.c
./include/turbojpeg/jcmaster.c
./include/turbojpeg/jdatadst-tj.c
./include/turbojpeg/jdapistd.c
./include/turbojpeg/turbojpeg.c
./include/turbojpeg/x64/simd.lib
./include/turbojpeg/x64/jsimd.h
./include/turbojpeg/x64/jsimd_x86_64.c
./include/turbojpeg/jcapimin.c
./include/turbojpeg/jdmarker.c
./include/turbojpeg/jdmerge.c
./include/turbojpeg/jdcolor.c
./include/turbojpeg/transupp.c
./include/turbojpeg/jfdctflt.c
./include/turbojpeg/jsimd_none.c
./include/turbojpeg/jcparam.c
./include/turbojpeg/jsimddct.h
./include/turbojpeg/jccoefct.c
./include/turbojpeg/jfdctint.c
./include/turbojpeg/jcsample.c
./include/turbojpeg/jconfigint.h
./include/turbojpeg/jcmainct.c
./include/turbojpeg/jchuff.c
./include/turbojpeg/jmemnobs.c
./include/turbojpeg/jcarith.c
./include/turbojpeg/jcprepct.c
./include/turbojpeg/jdhuff.h
./include/turbojpeg/jmemsys.h
./include/turbojpeg/jdmrg565.c
./include/turbojpeg/jccolor.c
./include/turbojpeg/jerror.c
./include/turbojpeg/jquant1.c
./include/turbojpeg/jcdctmgr.c
./include/turbojpeg/jsimd.h
./include/turbojpeg/jutils.c
./include/turbojpeg/turbojpeg.h
./include/turbojpeg/jconfig.h
./include/turbojpeg/x86/simd.lib
./include/turbojpeg/x86/jsimd.h
./include/turbojpeg/x86/jsimd_i386.c
./include/turbojpeg/jstdhuff.c
./include/turbojpeg/jcapistd.c
./include/turbojpeg/jmorecfg.h
./include/turbojpeg/jfdctfst.c
./include/turbojpeg/cdjpeg.h
./include/turbojpeg/jaricom.c
./include/turbojpeg/jdcolext.c
./include/turbojpeg/jdarith.c
./include/turbojpeg/jdmaster.c
./include/turbojpeg/jdct.h
./include/turbojpeg/jversion.h
./include/turbojpeg/README.txt
./include/turbojpeg/cderror.h
./include/turbojpeg/jinclude.h
./include/turbojpeg/jcomapi.c
./include/turbojpeg/jcphuff.c
./include/turbojpeg/transupp.h
./include/turbojpeg/jpeg_nbits_table.h
./include/turbojpeg/jdatadst.c
./include/turbojpeg/jmemmgr.c
./include/turbojpeg/jcmarker.c
./include/turbojpeg/jquant2.c
./include/turbojpeg/tjutil.h
./include/turbojpeg/jidctint.c
./include/turbojpeg/jdmrgext.c
./include/turbojpeg/jdapimin.c
./include/turbojpeg/jctrans.c
./include/turbojpeg/jidctflt.c
./include/turbojpeg/jcinit.c
./include/turbojpeg/jchuff.h
./include/turbojpeg/jdmainct.c
./include/turbojpeg/jdcoefct.c
./include/turbojpeg/jdsample.c
./include/turbojpeg/jdcol565.c
./include/turbojpeg/jidctred.c
./include/turbojpeg/jpegint.h
./include/turbojpeg/jdpostct.c
CR ./other/statics/Statics.hx
CR ./other/memory/TType.hx
CR ./other/memory/Memory.hx
CR ./other/memory/memory.hxml
./other/memory/.vscode/launch.json
./other/memory/.vscode/tasks.json
CR ./other/memory/Block.hx
CR ./other/haxelib/Run.hx
CR ./other/haxelib/haxelib.json
./other/cmake/FindSDL2.cmake
./other/cmake/cmake_uninstall.cmake.in
./other/cmake/linux32.toolchain.cmake
./other/cmake/FindLibUV.cmake
./other/cmake/FindDirectX.cmake
./other/cmake/FindTurboJPEG.cmake
./other/cmake/FindOggVorbis.cmake
CR ./other/uvsample/uvsample.hxproj
CR ./other/uvsample/UVSample.hx
./other/uvsample/uvsample.hxml
CR ./other/tests/Threads.hx
./other/tests/HelloWorld.hx
./other/benchs/Anonymous.hx
./other/benchs/_Startup.hx
./other/benchs/bench.air
./other/benchs/NBodies.hx
./other/benchs/BinaryTrees.hx
./other/benchs/Benchs.hx
./other/benchs/IntArray.hx
./other/benchs/Fib.hx
./other/benchs/FloatArray.hx
./other/benchs/Mandelbrot.hx
./other/benchs/benchs.hxml
./libs/mesa/mesa/GL.hx
CR ./libs/mesa/mesa/Context.hx
CR ./libs/mesa/Makefile
CR ./libs/mesa/haxe/System.hx
CR ./libs/mesa/haxe/AudioTypes.hx
CR ./libs/mesa/haxe/GLTypes.hx
CR ./libs/mesa/extraParams.hxml
CR ./libs/mesa/mesa.c
CR ./libs/mesa/sample/Test.hx
./libs/ui/CMakeLists.txt
./libs/ui/ui.vcxproj.filters
CR ./libs/ui/ui.vcxproj
CR ./libs/ui/ui_win.c
./libs/ui/ui_stub.c
./libs/video/video.sln
./libs/video/CMakeLists.txt
./libs/video/video.vcxproj.filters
./libs/video/video.c
./libs/video/video.vcxproj
./libs/ssl/ssl.vcxproj.filters
./libs/ssl/ssl.c
./libs/ssl/CMakeLists.txt
CR ./libs/ssl/ssl.vcxproj
./libs/CMakeLists.txt
./libs/fmt/CMakeLists.txt
CR ./libs/fmt/fmt.vcxproj.filters
./libs/fmt/sha1.c
CR ./libs/fmt/fmt.vcxproj
./libs/fmt/sha1.h
CR ./libs/fmt/mikkt.c
CR ./libs/fmt/fmt.c
./libs/openal/CMakeLists.txt
./libs/openal/haxelib.json
./libs/openal/ALImports.h
./libs/openal/openal/ALC.hx
./libs/openal/openal/AL.hx
./libs/openal/openal/Soft.hx
./libs/openal/openal/EFX.hx
./libs/openal/openal.c
./libs/openal/README.md
./libs/openal/openal.vcxproj.filters
./libs/openal/openal.vcxproj
./libs/openal/ALCImports.h
./libs/sqlite/CMakeLists.txt
./libs/sqlite/sqlite.c
./libs/sqlite/test/test.hxml
./libs/sqlite/test/bin/.gitignore
./libs/sqlite/test/run.bat
./libs/sqlite/test/classes/BasicTestCase.hx
./libs/sqlite/test/classes/ExceptionTestCase.hx
./libs/sqlite/test/classes/ResulSetTestCase.hx
./libs/sqlite/test/classes/Main.hx
./libs/sqlite/test/test.hxproj
./libs/sqlite/sqlite.vcxproj
./libs/sqlite/.gitignore
./libs/sqlite/sqlite.vcxproj.filters
CR ./libs/uv/uv.vcxproj
./libs/uv/CMakeLists.txt
CR ./libs/uv/uv.vcxproj.filters
CR ./libs/uv/uv.c
./libs/sdl/CMakeLists.txt
CR ./libs/sdl/gl.c
./libs/sdl/haxelib.json
./libs/sdl/GLImports.h
CR ./libs/sdl/sdl.c
CR ./libs/sdl/README.md
./libs/sdl/sdl/Window.hx
./libs/sdl/sdl/Event.hx
./libs/sdl/sdl/GL.hx
./libs/sdl/sdl/GameController.hx
./libs/sdl/sdl/SoundChannel.hx
./libs/sdl/sdl/Surface.hx
./libs/sdl/sdl/Cursor.hx
./libs/sdl/sdl/Sdl.hx
CR ./libs/sdl/sdl.vcxproj
CR ./libs/sdl/sdl.vcxproj.filters
CR ./libs/bullet/bullet.vcxproj.filters
./libs/bullet/CMakeLists.txt
./libs/bullet/haxelib.json
CR ./libs/bullet/Makefile
./libs/bullet/bullet.idl
CR ./libs/bullet/README.md
CR ./libs/bullet/bullet/Body.hx
CR ./libs/bullet/bullet/World.hx
CR ./libs/bullet/bullet/Native.hx
CR ./libs/bullet/bullet/Shape.hx
CR ./libs/bullet/bullet/Generator.hx
CR ./libs/bullet/bullet.sln
CR ./libs/bullet/sample/sample_js.hxproj
CR ./libs/bullet/sample/sample.html
CR ./libs/bullet/sample/sample_js.hxml
CR ./libs/bullet/sample/sample.hxml
CR ./libs/bullet/sample/sample.hxproj
CR ./libs/bullet/sample/Main.hx
CR ./libs/bullet/bullet.vcxproj
./libs/bullet/bullet.cpp
./libs/mysql/my_proto.o
./libs/mysql/my_proto.h
./libs/mysql/osdef.h
CR ./libs/mysql/mysql.vcxproj
./libs/mysql/mysq.vcxproj.filters
./libs/mysql/my_api.c
./libs/mysql/mysql.c
./libs/mysql/sha1.c
./libs/mysql/socket.c
./libs/mysql/my_proto.c
./libs/mysql/sha1.h
./libs/mysql/mysql.h
./libs/mysql/sha1.o
./libs/mysql/mysql.o
./libs/mysql/my_api.o
./libs/mysql/socket.h
./libs/mysql/socket.o
./libs/directx/CMakeLists.txt
./libs/directx/haxelib.json
./libs/directx/directx.h
./libs/directx/gamecontroller.c
CR ./libs/directx/directx.cpp
./libs/directx/directx.vcxproj.filters
CR ./libs/directx/directx.vcxproj
./libs/directx/dx/Window.hx
./libs/directx/dx/Event.hx
./libs/directx/dx/Resource.hx
./libs/directx/dx/Format.hx
./libs/directx/dx/Loop.hx
./libs/directx/dx/GameController.hx
./libs/directx/dx/Cursor.hx
./libs/directx/dx/Driver.hx
CR ./libs/directx/window.c
./README.md
CR ./libhl.vcxproj
./appveyor.yml
CR ./.gitignore
./Brewfile
CR ./hl.sln
./.travis.yml
CR ./src/jit.c
CR ./src/module.c
./src/debugger.c
CR ./src/hlc.h
CR ./src/std/thread.c
./src/std/unicase.h
CR ./src/std/buffer.c
CR ./src/std/track.c
CR ./src/std/process.c
./src/std/math.c
CR ./src/std/sys.c
./src/std/bytes.c
./src/std/array.c
CR ./src/std/cast.c
./src/std/fun.c
CR ./src/std/maps.c
./src/std/sys_android.c
./src/std/string.c
CR ./src/std/random.c
./src/std/regexp.c
CR ./src/std/socket.c
./src/std/sys_ios.m
./src/std/debug.c
CR ./src/std/error.c
CR ./src/std/types.c
./src/std/date.c
CR ./src/std/maps.h
CR ./src/std/file.c
./src/std/sort.h
./src/std/ucs2.c
CR ./src/std/obj.c
CR ./src/opcodes.h
CR ./src/alloc.c
CR ./src/main.c
./src/hlc_main.c
./src/hlmodule.h
CR ./src/hl.h
CR ./src/code.c
```

**Comment by dpeek** [comment]
Soooo rebasing this to master is going to get old quickly :)

**Comment by dpeek** [comment]
(No pressure though!)

**Comment by ncannasse** [comment]
Can you switch module.c and track.c to use the /other/ line endings ? the diff seems to contain most of the file for both :) I think we're good to merge after that.

**Comment by dpeek** [comment]
Fixed. `/include/pcre/config.h` was also more LF than CRLF so I switched that too.

**Comment by ncannasse** [comment]
Ok, sorry for the mess and thank you for helping with it :)

**Comment by dpeek** [comment]
\o/ you're welcome ;)

**Pull request merged**
